### ISSUE TITLE
Block Hell Mode

### ISSUE THREAD

**Issue by RickerMD** [theBGuy/GuysSoloLeveling#1]
My sorcs keep dying as son as they complete Den quest in hell mode. Is there a way to say to then keep on nightmare?
Ty!

**Comment by theBGuy** [comment]
Currently the level cap is set at 70. Are you making it to bloodraven or tristam? There's always gonna be some chickens/deaths in hell as its a harder mode but depending on where its failing at I could set it to magic find/level a bit before moving on

**Comment by RickerMD** [comment]
> Currently the level cap is set at 70. Are you making it to bloodraven or tristam? There's always gonna be some chickens/deaths in hell as its a harder mode but depending on where its failing at I could set it to magic find/level a bit before moving on

The most common chickens and deaths it's on Tristram. I got to says anyway, congrats on make it better than original. Keep up the good work. Bot is beautiful to watch. 

There is another channel other then guthub to discussing ideas and improves?

**Comment by theBGuy** [comment]
Yes, at the bottom of my readMe there is a link to my discord channel. Thank you! I'll keep that in mind and test out some new ideas for before tristram
