### ISSUE TITLE
Sorcs don't do Countess

### ISSUE THREAD

**Issue by RickerMD** [theBGuy/GuysSoloLeveling#2]
Hi. I have 4 sorcy running at this moment. Lightning, Blova, Meteorb and Cold. The problem is that only Cold is running Countess. Any reason to this? Ty!

**Comment by theBGuy** [comment]
What difficulty, level, and current build are each of the sorcs? In normal/nightmare sorcs will only run when the need gold or runes. In Hell, they shouldn't run at all at the moment but I'm gonna change that to allow blova/lightning to run count after final respec
