### ISSUE TITLE
Error when sorc dies or leave game with tier2

### ISSUE THREAD

**Issue by RickerMD** [theBGuy/GuysSoloLeveling#3]
Hi there. Whenever my sorc leves a game holding tier2, next game i got an error.
and is just change to tier1 and restart script thats it works again.
 
10:49:09 (SCL-SORC-2)  Error in Developer (developer.js #33) JSON.parse: unexpected end of data (Area: 1, Ping:250, Game: K-sorcr-hec-3)
10:49:09 (SCL-SORC-2)  Error in SoloLeveling (developer.js #39) Path is not defined (Area: 1, Ping:250, Game: K-sorcr-hec-3)

there is a way to tell the bot to always start and check if its on tier 1?

**Comment by aim2kill** [comment]
I believe tir1 and 2 u refering to normal/NM/Hell. She going back to normal to farm for gold because low gold and weapon are broken. Is a new way to help broken characters

**Comment by RickerMD** [comment]
I meant the other hand, the "cta" hand.

**Comment by theBGuy** [comment]
I'm don't think that error is related to that the bit leaveing off on the switch slot. it looks more like it failed to read a file

**Comment by RickerMD** [comment]
I will check it by tomorrow morning. Ty!

**Comment by RickerMD** [comment]
So, I Stand. Whenever the bot leaves the game wolding the second weapon in the next game he ends on an error and stalling on game until it ends. 
![image](https://user-images.githubusercontent.com/46378165/129445857-6b0e6580-37bb-4a37-b663-9c83c9e2d73a.jpeg)
![image](https://user-images.githubusercontent.com/46378165/129445860-2f394fcd-c472-4794-911f-ea051496eebc.jpeg)
![image](https://user-images.githubusercontent.com/46378165/129445869-5c762d51-f628-44be-9fae-77a5838b9654.jpeg)

**Comment by aim2kill** [comment]
All 4 sorcs have the same problem?

**Comment by theBGuy** [comment]
Is your sorceress using a lidless?

**Comment by RickerMD** [comment]
> Is your sorceress using a lidless? I just tried the same thing and mine works fine. yours is failing to read a file

Hand 1 spirit sword and spirit shield. Hand 2 wand with Low resist charges + lidless.

**Comment by theBGuy** [comment]
Alright, I added something new involving lidless recently and I believe that may be causing the issue. I should have a fix for it out later today

**Comment by theBGuy** [comment]
This should be fixed now, please let me know if it is so I can close out this issue

**Comment by theBGuy** [comment]
No response after 3 days, closing this out

**Comment by RickerMD** [comment]
That's solve it!
